import { Metadata } from "next";
import UserManagement from "./_components/user-management";

export const metadata: Metadata = {
  title: "POS | User Management",
  description: "Generated by create next app",
};

const Page = () => {
  return <UserManagement />;
};

export default Page;
